Conditions:
  ShouldSetupAPIGWCustomDomain: !And
    - !Not
      - !Equals
        - ${env:API_DOMAIN_NAME, ''}
        - ''
    - !Not
      - !Equals
        - ${env:ROUTE53_HOSTED_ZONE_ID, ''}
        - ''

Resources:
  APIGWCustomDomainCertificate:
    Condition: ShouldSetupAPIGWCustomDomain
    Type: AWS::ApiGateway::Certificate
    Properties:
      DomainName: ${env:API_DOMAIN_NAME, ''}
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: ${env:API_DOMAIN_NAME, ''}
          HostedZoneId: ${env:ROUTE53_HOSTED_ZONE_ID, ''}
  APIGWCustomDomain:
    Condition: ShouldSetupAPIGWCustomDomain
    Type: AWS::ApiGateway::DomainName
    Properties:
      DomainName: ${env:API_DOMAIN_NAME, ''}
      RoutingMode: API_MAPPING_ONLY
      DomainNameConfigurations:
        - EndpointType: REGIONAL
          SecurityPolicy: TLS_1_2
          IpAddressType: ipv4
          CertificateArn: !Ref APIGWCustomDomainCertificate

  APIGWCustomDomainMapping:
    Condition: ShouldSetupAPIGWCustomDomain
    Type: AWS::ApiGateway::ApiMapping
    Properties:
      ApiId: !Ref HttpApi
      DomainName: !Ref APIGWCustomDomain
      Stage: $default

  APIGWCustomDomaiDNSRecord:
    Condition: ShouldSetupAPIGWCustomDomain
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref APIGWCustomDomain
      Type: A
      HostedZoneId: ${env:ROUTE53_HOSTED_ZONE_ID, ''}
      AliasTarget:
        HostedZoneId: !GetAtt APIGWCustomDomain.RegionalHostedZoneId
        DNSName: !GetAtt APIGWCustomDomain.RegionalDomainName

