Resources:
  MealsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-${self:provider.stage}-meals-queue
      VisibilityTimeout: 130
      ReceiveMessageWaitTimeSeconds: 20
      RedrivePolicy:
        maxReceiveCount: 2
        deadLetterTargetArn: !GetAtt MealsDLQ.Arn

  MealsDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-${self:provider.stage}-meals-dlq
      MessageRetentionPeriod: 1209600 # 14 days
